var fullName = 'Jack Almadjian';
var isCool = true;
var totalPets = 10;
var unknown = null;
var never = undefined;
console.log('Value of fullName:', fullName);
console.log('Value of isCool:', isCool);
console.log('Value of totalPets:', totalPets);
console.log('typeof of fullName:', typeof fullName);
console.log('typeof isCool:', typeof isCool);
console.log('typeof totalPets:', typeof totalPets);
console.log('Value of unknown:', unknown);
console.log('typeof unknown:', typeof unknown);
console.log('Value of unknown:', never);
console.log('typeof unknown:', typeof never);
